
spring: 
  profiles:
    active:
    - dev

spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-glodon-dev

spring: 
  profiles: test
  application: 
    name: microservicecloud-config-glodon-test